### ISSUE TITLE
Eu, como desenvolvedor, gostaria de adicionar o Realm ao projeto

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#230]
## Descrição

Essa issue destina-se a adicionar o Realm para Database, no projeto e estudar como utilizá-lo, assim como estudar a possibilidade de ter 2 "instancias" de banco, uma para os dados fictícios e outra para os dados reais.

## Critérios de Aceitação

- [ ] Adicionar o Realm ao Projeto;
- [ ] Explicar se há como utilizar 2 instancias de database e como fazer isso.

**Comment by luis-gustavo** [comment]
@guibaldissera Tenho algumas dúvidas em relação a essa issue... Assim, tanto a parte de adicionar Realm ao projeto como ter duas "instâncias" eu já fiz, e exemplifiquei, como da pra ver nas imagens abaixo:
![](https://i.imgur.com/8Pnf515.png)
![](https://i.imgur.com/iEQBMDu.png)
![](https://i.imgur.com/P05LwWw.png)

Tem como criar duas configurações diferentes, uma para os dados mockados e uma para os dados reais.

O que mais deve ser feito ? Pois como ainda não existem as Models Globais e os dados mockados e nem os dados do servidor não tem como colocá-los no Realm... Outra coisa, não ficou muito claro, vou ter que preparar um dojô sobre realm ?
