### ISSUE TITLE
Eu, como DevOps, desejo deixar o servidor Nexte rodando em um IP e porta específica no docker.

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#231]
## Descrição

Essa issue destina-se a configurar o docker para executar o servidor Nexte em um IP e uma porta específica e fixa, para que a integração em mode de ambiente de desenvolvimento, seja sempre a mesma, evitando que seja necessário a alteração em código para direcionamento das requisições ao servidor.
Acho que a parte de Docker Machine faz configurações relacionadas à esse contexto.

## Critérios de Aceitação

- [ ] Deixar o servidor rodando em um IP e porta específica.

**Comment by Geovannioj** [comment]
Atualmente está issue é inviável, pois ao subir o servidor no docker, ele não fica visível para requisições, e a solução encontrada é subir o servidor em um host e fazer a requisição direto para ele.
