### ISSUE TITLE
Eu, como desenvolvedor, desejo estudar como realizar teste de integração

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#233]
## Descrição

Essa issue tem como objetivo realizar estudos e exemplificar como fazer testes de integrações, necessários quando usa-se um framework externo ao código.

## Critérios de Aceitação

- [ ] Estudar e preparar um DOJO sobre teste de integração;
- [ ] Exemplificar o teste.

**Comment by luis-gustavo** [comment]
https://stackoverflow.com/questions/31777188/android-methods-are-not-mocked-when-using-mockito
