### ISSUE TITLE
Eu, como usuário, desejo navegar pelo aplicativo através de uma TabBar (Bottom Navigation)

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#265]
## Descrição

Essa issue tem como objetivo adicionar uma TabBar (Bottom Navigation) ao aplicativo e fazer os ajustes necessários para que ela funcione, abrindo as activities que hoje já existem no app.

## Critérios de Aceitação

- [ ] A TabBar deve conter 3 botões (Feed, Desafio e Ranking, nessa ordem);
- [ ] Os botões, ao serem clicados, devem abrir a respectiva tela, sem criar uma pilha de telas.

**Comment by mbslet** [comment]
Oi gente, nós precisamos usar as imagens da tab bar do Nexte ios ou podemos improvisar? Se tiver que usar tem como mandar por favor

**Comment by miguelpimentel** [comment]
Então @mbslet, hoje falamos com nossa _design_ e ela passou o design da nossa tabBar. Ela vai ser parecida com existem em iOS. Entretanto os itens serão do mesmo tamanho, diferente da atual que o central é mais alto. Vou enviar essa temporária e pedir para ela me enviar ainda hoje. Até mais tarde coloco a mais nova aqui.

Enquanto isso, temos esta:

 [![IMG_D7_CE47_CAE3_AF-1.jpg](https://s31.postimg.cc/3rbbpli63/IMG_D7_CE47_CAE3_AF-1.jpg)](https://postimg.cc/image/vrff9vlmf/)

**Comment by mbslet** [comment]
Mas teria as imagens só deles?

**Comment by miguelpimentel** [comment]
Pode utilizar uma taBBar default, para não atrasar o desenvolvimento, depois substituímos os ícones. O mais importante é fazer o uso correto dela, visto que ela é o fluxo de telas da aplicação.

**Comment by miguelpimentel** [comment]
Como prometido, aqui estão os mockUps da TabBar: 

[![Screen_Shot_2018-05-09_at_14.36.18.png](https://s14.postimg.cc/sqrrnpsxd/Screen_Shot_2018-05-09_at_14.36.18.png)](https://postimg.cc/image/rbq6yzru5/)

[![Screen_Shot_2018-05-09_at_14.37.02.png](https://s14.postimg.cc/gowdtp9g1/Screen_Shot_2018-05-09_at_14.37.02.png)](https://postimg.cc/image/xpfa2dmh9/)

Sendo que esta é relevante para vocês:

[![Screen_Shot_2018-05-09_at_14.36.27.png](https://s14.postimg.cc/anyowrs0h/Screen_Shot_2018-05-09_at_14.36.27.png)](https://postimg.cc/image/tgak0coel/)

Caso desejem as assets me enviem mensagem privada no slack que exporto do Sketch para vocês,

**Comment by guibaldissera** [comment]
Os assets estão aí:
![ranking](https://user-images.githubusercontent.com/17801101/39836528-2025fd16-53aa-11e8-9482-f11ca0e577ed.png)
![feed](https://user-images.githubusercontent.com/17801101/39836529-20467a00-53aa-11e8-9682-ac7f59314a74.png)
![challenge](https://user-images.githubusercontent.com/17801101/39836530-2065061e-53aa-11e8-96c2-2a425f23178c.png)

**Comment by mbslet** [comment]
Oii, como eu adiciono os arquivos do drive ao projeto? Tipo, eu adicionava uma image assets e ele criava os tipo da imagens nas pastas certinhas do res e tals, entendeu mais ou menos a dúvida?

**Comment by miguelpimentel** [comment]
@mbslet, acho que te mandei e resposta no privado. Vamos mudar as configurações do taiga, porque não estamos sendo notificados por dúvidas em issues. Outra coisa, aqui está o hexadecimal da cor de fundo da tabas 1D1D1D, ou no rgb (29, 29, 29); rgb(29/256, 29/256, 29/256).
