### ISSUE TITLE
Eu, como usuário, quero poder excluir comentário na tela de lista de comentário

### ISSUE THREAD

**Issue by luis-gustavo** [fga-eps-mds/2018.1_Nexte#275]
## Descrição

Essa issue tem como objetivo excluir um comentário, na lista de comentários de uma atividade específica, quando o comentário for do usuário logado.

## Critérios de Aceitação

- [ ] O botão de excluir o comentário deve eliminar o comentário da tela;
- [ ] Só é possível excluir um comentário que o autor seja o usuário logado;
- [ ] A ação deve passar por toda a arquitetura, chegando na worker.

**Comment by aleronupe** [comment]
Pessoal, devemos criar uma classe mocker pra guardar a lista de comentários, simbolizando o servidor?
