### ISSUE TITLE
Eu, como usuário, gostaria de ver dados reais no ranking.

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#315]
## Descrição

Essa issue tem como objetivo adicionar integração ao servidor para fazer requisição do ranking de tenistas.

## Critérios de Aceitação

- [x] Adicionar integração ao servidor para chamar a rota de ranking;
- [x] Atualizar user realm com as informações vindas do servidor;
- [x] Criar a interface da worker para ser implementada no interactor, para dar update sem usar completion;
- [x] Chamar a interactor pela worker, antes de fazer a requisição ao servidor, e após atualizar o realm com as informações vindas do servidor.

**Comment by miguelpimentel** [comment]
Para fazer requisição é necessário incluir o seguinte header, sendo que o primeiro é para manipulação dos dados json. 

[![Screen_Shot_2018-05-21_at_18.37.13.png](https://s9.postimg.cc/ucf7hrjwv/Screen_Shot_2018-05-21_at_18.37.13.png)](https://postimg.cc/image/tzntbl1mz/)

De outra maneira, aqui temos um exemplo do header necessário para realizar requições, modelo em kotlin:

````
  val headers = mapOf("Content-Type" to "application/json",
                                    "Accept-Version" to "1.0.0")
```
