### ISSUE TITLE
Eu, como usuário, gostaria de ver uma tela inicial ao abrir o app.

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#324]
## Descrição

Essa issue destina-se a abrir uma tela quando o app iniciar. Isso só deve acontecer caso não exista usuário logado.

## Critérios de Aceitação

- [ ] Deve-se abrir uma tela ao iniciar o app caso não tenha usuário logado;
- [ ] Essa tela é uma tela de login;
- [ ] Deve-se seguir o design;
- [ ] Deve existir um botão para navegar no aplicativo sem fazer o login.

**Comment by helenagoulart** [comment]
Para setarmos que a tela inicial é a login, fazemos isso na OnCreate da Main Activity? Hoje o app abre e vai direto para a show profile, mas não achei nenhuma referência para isso lá para substituirmos pelo login. Rola uma luz de onde podemos setar a nossa tela inicial?
