### ISSUE TITLE
Eu, como desenvolvedor, desejo aplicar design à tela de alteração de perfil.

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#326]
## Descrição

Essa issue destina-se a aplicar o design na tela de alteração de perfil.

## Critérios de Aceitação

- [ ] Aplicar design na tela de alteração do perfil, seguindo os padrões da tela no Zeplin.

**Comment by guibaldissera** [comment]
<img width="374" alt="captura de tela 2018-05-27 as 16 15 07" src="https://user-images.githubusercontent.com/17801101/40589738-4862f626-61c9-11e8-9444-6d6adbd0196e.png">

**Comment by gabrielalbino** [comment]
@mbslet  @miguelpimentel  cara, seria muito legal se vcs corrigissem o bug de dar enter no campo do email xD
![image](https://user-images.githubusercontent.com/30835149/40633119-f9a18e0c-62c3-11e8-86d8-56f1c838fe47.png)

**Comment by mbslet** [comment]
Ok
