### ISSUE TITLE
Eu, como desenvolvedor, desejo aumentar a cobertura de testes na Scene Ranking.

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#350]
## Descrição

Essa issue tem como objetivo aumentar os testes na scene de ranking.

## Critérios de Aceitação

- [ ] Cobertura de Testes nessa Scene deve ser 92%.

**Comment by gabrielalbino** [comment]
@guibaldissera @miguelpimentel 
1 - como eu tiro a view do report do jacoco?
2 - a linha ```url.httpGet().responseJson { _, _, result ->``` tá dando uma exceção mesmo eu herdando da help for realm

exceção:
```
Exception in thread "Thread-1" java.lang.RuntimeException: Method getMainLooper in android.os.Looper not mocked. See http://g.co/androidstudio/not-mocked for details.
	at android.os.Looper.getMainLooper(Looper.java)
	at com.github.kittinunf.fuel.android.util.AndroidEnvironment.<init>(AndroidEnvironment.kt:10)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.github.kittinunf.fuel.core.EnvironmentKt.createEnvironment(Environment.kt:10)
	at com.github.kittinunf.fuel.core.FuelManager$callbackExecutor$2.invoke(FuelManager.kt:61)
	at com.github.kittinunf.fuel.core.FuelManager$callbackExecutor$2.invoke(FuelManager.kt:20)
	at com.github.kittinunf.fuel.util.ReadWriteLazyVal.getValue(Delegates.kt:14)
	at com.github.kittinunf.fuel.core.FuelManager.getCallbackExecutor(FuelManager.kt)
	at com.github.kittinunf.fuel.core.FuelManager.request(FuelManager.kt:132)
	at com.github.kittinunf.fuel.core.FuelManager.request(FuelManager.kt:64)
	at com.github.kittinunf.fuel.Fuel$Companion.request(Fuel.kt:103)
	at com.github.kittinunf.fuel.Fuel$Companion.get(Fuel.kt:32)
	at com.github.kittinunf.fuel.FuelKt.httpGet(Fuel.kt:116)
	at com.github.kittinunf.fuel.FuelKt.httpGet$default(Fuel.kt:116)
	at com.nexte.nexte.RankingScene.RankingWorker.getUsersInRanking(RankingWorker.kt:46)
	at com.nexte.nexte.RankingScene.RankingInteractor.getPlayersRanksForScene(RankingInteractor.kt:30)
	at com.nexte.nexte.RankingScene.RankingInteractorTest$testGetPlayersRanksForScene$1.invoke(RankingInteractorTest.kt:55)
	at com.nexte.nexte.RankingScene.RankingInteractorTest$testGetPlayersRanksForScene$1.invoke(RankingInteractorTest.kt:12)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)


```

**Comment by luis-gustavo** [comment]
### 1.
Dentro do arquivos build.grade(app), localiza a "função" **task jacocoTestReport(type: JacocoReport, dependsOn: ["clean", "testDebugUnitTest"])**. Dentro de **classDirectories** vá em **excludes** e adicione:  '\*\*/\*Fragment\*.\*' e '\*\*/\*View\*.\*'

### 2.
Jogue o código que "chama essa requisição" dentro de **thread { }.join**.

Por exemplo, se é algum método da worker:
```kotlin
thread {
this.worker?.blabla()
}.join()
```

**Comment by larissa-sales** [comment]
![image](https://user-images.githubusercontent.com/28152907/41011337-c9525f2e-6912-11e8-8713-fad3b549715a.png)

como testa esses métodos?: 
- RankingWorker.getUsersInRanking.new Function3() {...}
- RankingWorker.getUsersInRanking.1..special..inlined.sortedBy.new Comparator() {...}

**Comment by miguelpimentel** [comment]
@larissa-sales vou abrir o projeto e dar uma olhada, é urgente? Se for manda foto aqui, estou trabalhando com o servidor.

**Comment by gabrielalbino** [comment]
@miguelpimentel são decorrentes das linhas 41 e 46 [desse arquivo](https://github.com/fga-gpp-mds/2018.1_Nexte/blob/dev/project/app/src/main/java/com/nexte/nexte/RankingScene/RankingWorker.kt)

**Comment by miguelpimentel** [comment]
Quais métodos? Estou confuso. É relacionado ao Fuel ou Realm? Algo assim?

**Comment by gabrielalbino** [comment]
Um eh o httprequest o outro eh o sort
Ele considera como metodos que devem ser testados (?)
RankingWorker.getUsersInRanking.new Function3() {...} -> esse eh o HttpRequest
RankingWorker.getUsersInRanking.1..special..inlined.sortedBy.new Comparator() {...} -> esse eh o sort

**Comment by gabrielalbino** [comment]
Mas eles só sao chamados dentro do metodo da worker

**Comment by miguelpimentel** [comment]
Esse http acredito que seja do Fuel, de qualquer forma ele o @luis-gustavo mostrou como testar isso com _thread join_. A editProfile tem teste exemplificado com completions assim como a login Worker.

**Comment by miguelpimentel** [comment]
exemplo:

```

    @Test
    fun testAuthenticateUserTokenEmpty(){
        //prepare
        val userName = "luis-gustavo"
        val password = "123456"
        val request = LoginModel.Authentication.Request(userName = userName, password = password)
        val tokenId = ""

        //call
        this.worker?.authenticateUser(request = request, completion = { response ->

            //assert
            assertEquals(response.tokenId, tokenId)
        })
    }
```

**Comment by gabrielalbino** [comment]
Tá, to no desktop agora posso explica com mais detalhes
seguinte, [aqui](https://gitlab.com/Baldissera/2018.1_Nexte/-/jobs/73040023/artifacts/browse/project/app/build/reports/jacocoTestReport/html/) tá o report do jacoco (expira em 5 horas, go fast dude)
Se você abrir a [worker da cena do ranking](https://baldissera.gitlab.io/-/2018.1_Nexte/-/jobs/73040023/artifacts/project/app/build/reports/jacocoTestReport/html/com.nexte.nexte.RankingScene/RankingWorker.html#dn-a) vai ver que o teste que usa o fuel já tá testado em 2 dos 5 caminhos possíveis.

Um dos outros caminhos que poderiam ser testados é setando o userManager pra null, mas isso causa uma exceção de nullpointerexception porque quem desenvolveu a classe deu um _user!!_, esse é primeiro problema mas contorna-lo é fácil

Os outros 4 caminhos que podem ser testados estão dentro do HttpRequest, então temos a seguintes conclusões até agora:
1 - Não é possível testar todos os caminhos desse método pois a resposta do servidor é _imprevisivel_

2- O método que usa o HTTPRequest já tá testado em partes


Ok, partindo dessas conclusões voltaremos a analise da cena do ranking, ela possui duas funções misteriosas sem teste, que são

nome da classe |   | Missed instructions coverage |   | missed branches coverage| missed | cxty | missed | lines | missed | methods | missed | classes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
RankingWorker.getUsersInRanking.1..special..inlined.sortedBy.new Comparator() {...} |   | 0% |   | n/a | 2 | 2 | 3 | 3 | 2 | 2 | 1 | 1
RankingWorker.getUsersInRanking.new Function3() {...} |   | 0% |   | 0% | 9 | 9 | 13 | 13 | 2 | 2 | 1 |  

Fazendo uma analise desses métodos, é possivel descobrir que o primeiro tem a seguinte estrutura:
`compare(Object, Object)`, isso é, é uma comparação, e analisando pelo nome dele (RankingWorker.getUsersInRanking.1..special..inlined.sortedBy.new Comparator()) dá pra ver claramente que se trata do metodo sort que eu usei para organizar o usuário a partir dos rankings.
Ou seja, é um método da classe List que eu usei pra ordenar os users e ele tá pedindo pra eu testar.. *(Como testa?)*

Analisando o seguinte método, ele tem a seguinte estrutura:
nvoke(Request, Response, Result)
Isso é o httpRequest, que é usado somente dentro do método (que, como foi explicado anteriormente, jpa foi testado!)

é isto amigos, espero que entendam a duvida agora, que é como testar [esse bixo aqui](https://baldissera.gitlab.io/-/2018.1_Nexte/-/jobs/73040023/artifacts/project/app/build/reports/jacocoTestReport/html/com.nexte.nexte.RankingScene/RankingWorker$getUsersInRanking$1.html#dn-a) e [esse outro bixo aqui](https://baldissera.gitlab.io/-/2018.1_Nexte/-/jobs/73040023/artifacts/project/app/build/reports/jacocoTestReport/html/com.nexte.nexte.RankingScene/RankingWorker$getUsersInRanking$1$$special$$inlined$sortedBy$1.html#dn-a)

**Comment by luis-gustavo** [comment]
@gabrielalbino Ele não está testando isso pois nunca passa nessas linhas(ele não consegue fazer essa requisição no ambiente de testes, eu acho). Creio que você deve estar rodando isso dentro de **thread { }.join()**, se for ele simplesmente gera a excessão quando chega nessa parte e continua o teste, por isso nunca passa nessas linhas. Infelizmente eu não estou com tempo para descobrir uma maneira de testar isso hoje. Recomendo dar uma olhada em [**Fuel test mode**](https://github.com/kittinunf/Fuel), é a única coisa que já vi que talvez possa funcionar. Caso esteja dando muito trabalho ou não consiga testar isso, bola pra frente vai pra próxima issue.

**Comment by luis-gustavo** [comment]
Outra coisa que pode facilitar testar o comparator, é tirar ele de dentro do block do httpRequest. Modulariza, criando outro método ou então passando ele pro método do json, que ai você consegue testar
