### ISSUE TITLE
Eu, como desenvolvedor, desejo aumentar a cobertura de testes na Scene Comment.

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#351]
## Descrição

Essa issue tem como objetivo aumentar os testes na scene de comment.

## Critérios de Aceitação

- [ ] Cobertura de Testes nessa Scene deve ser 92%.

**Comment by mbslet** [comment]
Isso ta mostrando na cobertura da Comments Interactor

![screenshot from 2018-06-08 20-34-46](https://user-images.githubusercontent.com/30835147/41185106-75ee00a4-6b5b-11e8-924b-96f328ad42c8.png)
 
Ai eu fiz algo do tipo pra cada um dos metodos, ja que tinha que testar o response

![screenshot from 2018-06-08 20-36-58](https://user-images.githubusercontent.com/30835147/41185137-b67bbb3e-6b5b-11e8-9851-8f4c3fbce937.png)


E eu não sei pq continua igual os testes...

**Comment by guibaldissera** [comment]
Tá, mas tu está tentando testar o que? Qual método?
