### ISSUE TITLE
Eu, como desenvolvedor, desejo aumentar a cobertura de testes na Scene Like List.

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#354]
## Descrição

Essa issue tem como objetivo aumentar os testes na scene de like list.

## Critérios de Aceitação

- [ ] Cobertura de Testes nessa Scene deve ser 92%.

**Comment by mbslet** [comment]
No teste da LikeListPresenterTest, tem uma parada que precisa ser testada que é o LikeListPresenter(), ai eu tentei de uma forma mas, embora passou, não foi certo pq não mudou nada e eainda está em 0%, alguem sabe como resolver isso?

**Comment by mbslet** [comment]
![screenshot from 2018-06-08 00-26-35](https://user-images.githubusercontent.com/30835147/41137655-b70f4a88-6ab2-11e8-87ba-6578c268cf01.png)

**Comment by luis-gustavo** [comment]
@mbslet O que você fez para testar isso ? Pelo que mostra no arquivo ele está pedindo para você instaciar a Presenter "vazia"(sem os parâmetros do construtor). Você fez isso ? Se não fez tenta ai e me fala o que deu
