### ISSUE TITLE
Fabric para android

### ISSUE THREAD

**Issue by arthurbdiniz** [fga-eps-mds/2018.1_Nexte#372]
Ola grupo Nexte, sou do grupo @fga-gpp-mds/reabilitacao-motora  e conforme pedido pela @RochaCarla na aula dessa terça-feira que fosse implementado ferramentas que fizessem benchmark para a aplicação. Como tenho contato com android, queria sugerir um plugin/ferramente de Crashlytics.

A ferramenta se chama  [Fabric](https://get.fabric.io), serve para fazer um acompanhamento sobre a aplicação em tempo real no quesito qualidade e feedback. 
Quando usado qualquer Crash dentro do aplicativo um e-mail vai ser enviado para o time mostrando em qual parte do aplicativo aconteceu a falha e possíveis causas do problema, alem disso os Crashs podem ser acompanhados no próprio site.

![cash](https://user-images.githubusercontent.com/18387694/41073571-45fadfc0-69da-11e8-804f-6a8b29b8e57c.png)

![2](https://user-images.githubusercontent.com/18387694/41073618-8182e5a6-69da-11e8-8806-98d74e894c1b.png)

# Instalação para Android
![1_n2lywsmfz-yvrosjf3brpw](https://user-images.githubusercontent.com/18387694/41073675-cb6630e2-69da-11e8-8c82-971e2406a8f6.png)
![1_uy2jifo4djbji30nq8bxta](https://user-images.githubusercontent.com/18387694/41073671-cae5d582-69da-11e8-87f3-355a49e6e8d6.png)
![1_hatedriaabeva-famvgbhg](https://user-images.githubusercontent.com/18387694/41073672-cb0605e6-69da-11e8-9166-53745a7d0b70.png)
![1_dhesncyzjkvqj057_xatew](https://user-images.githubusercontent.com/18387694/41073673-cb232112-69da-11e8-8278-f3aab96f2c56.png)
![1_dbmlmrv3jvgwyj7wr77hmq](https://user-images.githubusercontent.com/18387694/41073674-cb448ef6-69da-11e8-81b6-839fb0bd5c91.png)

# Configurando Fabric Beta para Android

## Ir em [(https://fabric.io/features/distribution](https://fabric.io/features/distribution)

![1_33ljtsusq6rn-uug75merg](https://user-images.githubusercontent.com/18387694/41073765-1fcbf4d2-69db-11e8-9ff2-e986213d8a4d.png)

Nessa parte pegaremos o ```api_token``` e ```build_secret``` para colocarmos dentro do ```FastFile```

Ficaria assim:

```
desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics(
       # keys for organization: Hardroid Arce’s Projects
       api_token: "dsfgdsgfdfgdsgsdfgsdgdsgsdgsdg",
       build_secret: "3116f167ee9aad0b018efed4bsgfgsdgsdgsdgsdg4d3c5673cbb88c6"
   )
end

```

Tudo pronto agora só abrir o site do Fabric ou acompanhar os Crashs por e-mail para abertura de issues e correção dos bug!

Qualquer duvida podem me marcar aqui na issue ou entrar em contato comigo pelo
Github: @arthurbdiniz
Email: arthurbdiniz@gmail.com
Telegram: @arthurbdiniz
 
Ou pessoalmente durante a aula de EPS.

Espero ter ajudado! 👍

**Comment by miguelpimentel** [comment]
Valeu @arthurbdiniz , vamos ver a viabilidade de implementar isso até a release 2. Mas, muito obrigado. FEEDBACK tooop!
