### ISSUE TITLE
Eu, como usuário, desejo visualizar a tela de tenistas disponíveis de forma mais bonita.

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#375]
## Descrição

Essa issue tem como objetivo aplicar design na tela de lista de tenistas disponíveis.

## Critérios de Aceitação

- [ ] Aplicar design na lista de tenistas.

**Comment by lorranyh** [comment]
@guibaldissera as círculos coloridos deverão ser amostrados na expansão da célula também?
