### ISSUE TITLE
Eu, como usuário, desejo visualizar de forma mais intuitiva a tela de perfil de tenistas.

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#376]
## Descrição

Essa issue tem como objetivo aplicar design diferente para visualização do perfil do tenista, quando o perfil é do usuário logado e quando é perfil de outro tenista.

## Critérios de Aceitação

- [ ] Quando abrir o perfil logado, mostrar as informações segundo o Zeplin para Logado;
- [ ] Quando abrir o perfil de outro tenista, mostrar as informações segundo o Zeplin para tenista externo;

**Comment by gabrielalbino** [comment]
This issue was stoled by H4K3R-4LB1N0

**Comment by guibaldissera** [comment]
Aqui estão os dois estados para perfil do usuário logado:
<img width="400" alt="captura de tela 2018-06-14 as 21 07 39" src="https://user-images.githubusercontent.com/17801101/41444109-473d44fc-7017-11e8-951c-46b3687eb681.png">
<img width="400" alt="captura de tela 2018-06-14 as 21 02 13" src="https://user-images.githubusercontent.com/17801101/41444110-475bf7c6-7017-11e8-97dd-684f7698b715.png">

Aqui estão os dois modos para outros tenistas:
<img width="400" alt="captura de tela 2018-06-14 as 21 02 25" src="https://user-images.githubusercontent.com/17801101/41444099-37ed7db4-7017-11e8-8d8f-00fc64f6d8f7.png">
<img width="400" alt="captura de tela 2018-06-14 as 21 02 46" src="https://user-images.githubusercontent.com/17801101/41444100-380e809a-7017-11e8-83c3-efabfc2e49e0.png">


Nota-se que o botão da direita tem comportamento diferente para cada perfil.
