### ISSUE TITLE
Eu, como tenista, desejo ver os gráficos mais bonitos, e com mais informações.

### ISSUE THREAD

**Issue by guibaldissera** [fga-eps-mds/2018.1_Nexte#387]
## Descrição

Os gráficos devem ser apresentados de forma mais fiel e agradável aos usuário, deve-se seguir o design proposto.

## Critérios de Aceitação

- [ ] Cores de acordo com o sketc/zeplin
- [ ] Novas linhas para inserção de dados
- [ ] Adição de legendas

**Comment by larissa-sales** [comment]
@guibaldissera quais seriam os critérios pra essa história? qual informação falta no primeiro gráfico além das legendas?

**Comment by miguelpimentel** [comment]
Responde não, @guibaldissera
