### ISSUE TITLE
Eu, como desenvolvedor, gostaria de usar e testar o aplicativo para ver se todas as funcionalidades estão funcionando como deveriam e encontrar possíveis bugs

### ISSUE THREAD

**Issue by luis-gustavo** [fga-eps-mds/2018.1_Nexte#429]
## Descrição
Essa issue destina-se a testar o aplicativo de forma a ver se não tem nenhuma funcionalidade com comportamento estranho e para encontrar e reportar possíveis bugs.

## Critérios de Aceitação
Não se aplica.

**Comment by aleronupe** [comment]
**~Bug 1~** **(Resolvido)**

A Tela está girando, pelo que me lembro, deveria ficar estática de forma vertical.
![image](https://user-images.githubusercontent.com/37146204/41630223-4baa01c4-7404-11e8-995d-9dc9b09066bc.png)

**~Bug 2~** **(Resolvido)**

Primeira célula do _Feed_ não é passível de curtir, bem como algumas outras aleatórias.
![image](https://user-images.githubusercontent.com/37146204/41630270-874608b8-7404-11e8-9e1e-e421a28f30f3.png)

**~Bug 3~** **(Resolvido)**

As células do _Feed_ que podem ser curtidas não estão integrando com os dados mockados, de forma que, após serem curtidas, a célula sofre um _refresh_ porém com dados anteriores aos mockados.
_Bônus:_ E aquela imagem de fundo do _ic.launcher_ ?
![image](https://user-images.githubusercontent.com/37146204/41630404-26251cc6-7405-11e8-8c4b-c045e8aff9d7.png)

**~Bug 4~** **(Resolvido)**

A Tela de curtidas não tem nenhum jogador sendo mostrado, mesmo após curtir a atividade no feed.
![image](https://user-images.githubusercontent.com/37146204/41630758-1a53f938-7407-11e8-8ed3-9adb2d01d660.png)

**~Bug 5~** **(Resolvido)** 

O Design da tela de comentários está permitindo ao teclado a sobreposição da barra de inserção de texto. 
![image](https://user-images.githubusercontent.com/37146204/41630860-a0eb63aa-7407-11e8-879e-c48efa768338.png)

**~Bug 6~** **(Resolvido)**

Tá rolando um _crash_ no app se são realizados alguns cliques na tela de comentários
![image](https://user-images.githubusercontent.com/37146204/41630878-b92f0b42-7407-11e8-86ba-3541ff41467d.png)

**~Bug 7~** **(Resolvido)**

Se o usuário abre a tela de edição de perfil e depois vai conferir os _desafios enviados_ / _lista de jogadores_ a tela anterior permanece

![image](https://user-images.githubusercontent.com/37146204/41630909-e767ca94-7407-11e8-88e8-04691ed9feac.png)

**Bug 8**

Não dá, nunca, pra cancelar um desafio. Nem pra enviar.
![image](https://user-images.githubusercontent.com/37146204/41630956-3d49d3c6-7408-11e8-8e3d-f6b179640275.png)

**~Bug 9~** **(Resolvido)**

O Banco de dados de imagens está retornando uns tons monótonos e deixando de retornar várias das imagens que o popularam. Se estiver programado pra fazer isso propositalmente, ignorem.

![image](https://user-images.githubusercontent.com/37146204/41630972-5263f3ae-7408-11e8-9fa2-20597cd9ee7b.png)

**~Bug 10~** **(Resolvido)**

Essa imagem substituiu o _ic.launcher_ em muitos lugares.
(Quem quer que tenha sidx x responsável, saiba que já fiz isso antes, dá cá um abraço)
![image](https://user-images.githubusercontent.com/37146204/41631004-9e954ffc-7408-11e8-900d-95a89a11a41d.png)


**Bug 11**

Depois que se percorre alguns _fragments_ , a lista de players não mostra os players disponíveis
![image](https://user-images.githubusercontent.com/37146204/41631246-f1073a38-7409-11e8-9a84-cacd7e84a5de.png)


**Bug 12**

Quando a célula do usuário atual vai passar pelos limites da tela, ao ficar fixa em tela (seja na parte superior ou inferior ao dispositivo), a cor da célula, bem como seu formato (antes com bordas arredondadas) são alterados.

![image](https://user-images.githubusercontent.com/37146204/41631300-4153b980-740a-11e8-920b-35194e6d6dca.png)

**Bug 13**
Os indicadores de resultado de jogos (as bolinhas coloridas) do Segundo colocado (que deveria possuir todas amarelas, pelo que me lembro) e do usuário atual estão nulas.

![image](https://user-images.githubusercontent.com/37146204/41631380-ae1ab6b8-740a-11e8-9706-d9883d35f444.png)

**Bug 14**
Os anos dos jogos mockados mostrados no perfil estão sendo enviados com valores incorretos.

![image](https://user-images.githubusercontent.com/37146204/41631445-0c6677ac-740b-11e8-8ff9-1427b4729106.png)


**~Bug 15~** **(Resolvido)**

Depois que se acessa a função de editar perfil, a tela de edição aparece na transição de fragments.
Será que tem algo a ver com o bug 7? ¯\_(ᵔ ͜ʖᵔ)_/¯
_Ps: fico devendo imagens dessa pq fica difícil tirar_



**Bônus**
* O Próprio perfil tem a opção de pegar o contato. (Previsto em design)

**Comment by helenagoulart** [comment]
**Bug 1 resolvido**

**Comment by luis-gustavo** [comment]
**Bug 13 também já foi resolvido**

**Comment by larissa-sales** [comment]
Como complemento do **Bug 7**, a tela de comentários também aparece nos fragments de desafio. Talvez outras telas apareçam de forma errada nos fragments de desafio também
![image](https://user-images.githubusercontent.com/28152907/41821564-1f6bc7a6-77b9-11e8-9249-1ac39b7bb531.png)

**Comment by larissa-sales** [comment]
**Bug 16** 
O app dá crash ao tentar abrir a tela do próprio perfil (usuário logado). Só é possível abrir perfil se for de outro jogador.
