### ISSUE TITLE
Eu, como usuário, quero ver meu  perfil de usuário para visualizar minhas informações

### ISSUE THREAD

**Issue by luis-gustavo** [fga-eps-mds/2018.1_Nexte#92]
## Descrição
Essa funcionalidade permitirá ao usuário acessar aos dados do seu perfil, permitindo-o  fazer modificações em qualquer uma das opções apresentadas.

## Critérios de Aceitação

 - [ ]  É preciso apresentar o nome, clube pertencente, email, foto de perfil, idade e posição do ranking
 - [ ] Deve existir uma classe "Player" aninhada à model, contendo os atributos que foram as informações do usuário

**Comment by luis-gustavo** [comment]
@mbslet Colocar aqui critérios de aceitação e descrição.

**Comment by mbslet** [comment]
Na questão das fotos do perfil, vai ser provida de um link, um upload de algum arquivo do usuário ou de uma sistema de mesclagem com outro app (como o facebook)?

**Comment by aleronupe** [comment]
Podemos criar uma classe aninhada (player) para trabalhar com os dados do usuário? Ou, para esse requisito não seria interessante essa implementação?

**Comment by miguelpimentel** [comment]
@aleronupe , seria uma boa ideia criar uma classe aninhada para trabalhar com o usuário nessa tela! Acho legal colocar como critério de aceitação.

**Comment by miguelpimentel** [comment]
@mbslet , então depende. Mas a princípio isso será oriundo do nosso servidor. Nesse momento, não pensamos e discutimos o login com o facebook, até porque o cadastro seria feito por nós mesmos.

**Comment by mbslet** [comment]
Como crio um arquivo xml para o ShowProfile? Eu sei onde fica para criar mas não sei o que escolher ali

**Comment by miguelpimentel** [comment]
@mbslet, te mostro pessoalmente. Hoje ficarei até às 13 na FGA

**Comment by luis-gustavo** [comment]
@mbslet  @aleronupe  Essa história está em "To do" ainda ?

**Comment by mbslet** [comment]
Dúvida em criar um xml, quem puder tirá-la, agradeço

**Comment by miguelpimentel** [comment]
[![IMG_0215_3.jpg](https://s17.postimg.org/61puwv2sf/IMG_0215_3.jpg)](https://postimg.org/image/anlz57obf/)

E depois, lembrando que desta forma, você irá criar uma Activity vazia e um arquivo XML, referente a isso:

[![IMG_4207_2.jpg](https://s17.postimg.org/it413c9zj/IMG_4207_2.jpg)](https://postimg.org/image/fz0vpw7t7/)

**Comment by mbslet** [comment]
Como podemos mostrar nossa activity no celular ao invés da activity main? Tentamos usar o mesmo comando da activity main só que "SetContentView(R.layout.activity_show_profile)"

**Comment by aleronupe** [comment]
A Gente teve bastante dificuldade com xml na main activity, não estamos conseguindo implementar as funções de mostrar a tela do aplicativo.

**Comment by Geovannioj** [comment]
@mbslet  e @aleronupe, acho que por enquanto vocês podem colocar um botão na main activity que leva para página e perfil do usuário, e vejam este vídeo: https://www.youtube.com/watch?v=qzDML84PyZQ ele é um tutorial vai ajudar vocês a implementarem essa transição de uma tela para a outra.

**Comment by Geovannioj** [comment]
@aleronupe, cria uma outra activity e faz a página o perfil o usuário nela.

**Comment by miguelpimentel** [comment]
@Geovannioj, acho que seria melhor só eles mudares a referência da tela no AndroidManifest.xml, para evitar retrabalho no futuro. Mas, lembre-se que não é para commitar esse Arquivo, seria apenas para teste. Acho que foi um erro muito grande a gente não colocar como critério de aceitação a criação de uma View para cada cena na sprint passada. Entretanto, vocês consegue mostrar a View que vocês quiserem só mudando essa configurações no Android Manifest:

[![IMG_1926.png](https://s17.postimg.org/hk2tw1xgf/IMG_1926.png)](https://postimg.org/image/bvwj55t3v/)

**Comment by mbslet** [comment]
Está dando um erro por causa do R na "setContentView(R.layout.activity_main)", dizendo "unresolved reference: R ", achamos muitos erros semelhantes na net mas as formas tentadas para solucionar não deram muito certo

**Comment by gabrielalbino** [comment]
Adicione um 
Import com.nexte.nexte.R

**Comment by mbslet** [comment]
Ah tentamos isso mas do jeito errado hahah, mas ainda assim não deu

**Comment by gabrielalbino** [comment]
Tenta dar build -> build solution no menu superior

Em Qua, 4 de abr de 2018 23:06, Letícia Meneses <notifications@github.com>
escreveu:

**Comment by aleronupe** [comment]
@luis-gustavo Dentre os critérios de aceitação, nós colocamos que o usuário será capaz de editar as informações de perfil, mas vimos que, no road map, isso está para a próxima sprint. Podemos alterar o critério de aceitação para se adequar à nossa sprint?

**Comment by luis-gustavo** [comment]
@aleronupe Pode sim! pra essa _sprint_ era só visualizar mesmo. E os critérios de aceitação ficaram ótimos.
